### PR TITLE
Clean up CI, add Python 3.8

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request cleans up our CI on Travis and AppVeyor and adds builds for Python 3.8.

### CODE REVIEW

**Comment by mcflugen** [comment]
@mdpiper In addition to the CI clean-up, I've also, I think, fixed the issue you were having with the tester crashing while it was collecting the tests. I'm now able to run the test for `pymt_hydrotrend:Hydrotrend` (which was also crashing) but I haven't tested your components.

**Comment by mdpiper** [comment]
@mcflugen Awesome! Thank you for doing this. I'll try it on my Fortran components. Just to be careful, is the tester run with the classname `pymt_hydrotrend.bmi:Hydrotrend`?

**Comment by mcflugen** [comment]
@mdpiper Before I answer, could you please have a look at the output of`bmi-test --help` first? I've updated the help message and would like to see if it's actually helpful. It should answer your question. If not, please let me know.

**Comment by mcflugen** [comment]
@mdpiper I'm going to merge this pull request since it was really just for CI stuff. If your problem isn't fixed, I'll create a new PR.

**Comment by mdpiper** [comment]
@mcflugen It works!

**Pull request merged**
